[metadata]
name = wolumeicon
version = 0.1
author = Dino Duratović
author_email = dinomol@mail.com
url = https://github.com/dglava/wolumeicon
description = Volume icon for the system tray
license = GPL3
license_files = LICENSE

[options]
install_requires =
    dbus-python
    PyQt6

[options.entry_points]
console_scripts =
    wolumeicon = wolumeicon:run
